### ISSUE TITLE
1.21已知问题

### ISSUE THREAD

**Issue by ghost** [yunshuangqwq/mccaoyuantxwiki#7]
**问题描述**
1.21已知问题:
1.领地名字成变量
2.NPC名字异常
3.称号异常

**问题截图**
![](https://img.yunr.us.kg/api/cfile/AgACAgUAAyEGAASO2xA4AAMmZx-WYzZN7H6DT-ppohQXLv9JwAwAAsDCMRsPifhUBxGuUQmonT8BAAMCAAN4AAM2BA)

![](https://img.yunr.us.kg/api/cfile/AgACAgUAAyEGAASO2xA4AAMnZx-WkP1wlu74nZr_CTZ0ItTVwcUAAsHCMRsPifhUlyKjfQupjSwBAAMCAAN3AAM2BA)

![](https://img.yunr.us.kg/api/cfile/AgACAgUAAyEGAASO2xA4AAMoZx-WwxCzly-thmwa8n406tWUOpIAAsLCMRsPifhUghbunm45G14BAAMCAAN4AAM2BA)

**您使用的是什么客户端**
请输入您使用的客户端(如PCL)：官启

**Comment by aoc46hiabck4678wofh** [comment]
领地名字正常了，mpc名字没法修，称号插件不支持1.21

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/20b6e14b-da58-4250-a4e0-bbc53a61545f)
